import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "@/components/Header";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

const inter=Inter({subsets:['latin']})

export const metadata = {
  title: "CAREER BUDDY - Your career partner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme:dark
    }}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} `}
        >
          <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              {/* header */}
              <Header/>
              <main className="min-h-screen">
                {children}
              </main>
              <Toaster richColors />
              {/* footer */}
              <footer className="h-36 flex justify-center items-center bg-black">
                <div className="text-3xl p-10">
                  Made by industry experts while drinking
                </div>
              </footer>
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
